name: armTemplateDeployment
on:
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Storage Account
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionID: "db8c53d0-0187-4af7-88cd-5d950caf9a9c"
          resourceGroupName: 'HPE-IaC-RG'
          region: "centralus"
          template: ./arm-templates/storageaccount.json
          deploymentName: "HPE-IaC-RG-02"
